version: '3'

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - TZ=Asia/Tokyo
